# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-yaml
        args:
          - --unsafe
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: check-shebang-scripts-are-executable
    -   id: check-executables-have-shebangs
# Will run a bunch of standard pre-commit hook for jupyter notebook
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.4
  hooks:
    - id: nbqa-ruff
      args: [--ignore=D, --fix, --line-length=120]
# Will autoformat the doc
- repo: https://github.com/myint/docformatter
  rev: v1.5.0
  hooks:
    - id: docformatter
      args:
        - --in-place
        - --wrap-summaries=120
# Ruff: black, isort, flake8, pycodestyle and bandit rules
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.1.3'
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix]
# Check if the docstring respect google format. Might be added in ruff
- repo: https://github.com/jsh9/pydoclint
  rev: 0.4.1
  hooks:
    - id: pydoclint
      args:
        - --style=google
        - --exclude=cli.py|libs/[A-Za-z0-9-]+/tests/|libs/research/archive/|libs/skynet/skynet/testing.py
        - --arg-type-hints-in-docstring=false
        - --check-return-types=false
        - --check-yield-types=false
