# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      -   id: check-yaml
          args:
            - --unsafe
      -   id: check-json
      -   id: check-toml
      -   id: check-added-large-files
      -   id: detect-private-key
      -   id: debug-statements
      -   id: check-merge-conflict
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
  # Ruff: black, isort, flake8, pycodestyle and bandit rules
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.6.9'
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  # Check if the docstring respect google format. Might be added in ruff
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.4.1
    hooks:
      - id: pydoclint
        args:
          - --style=google
          - --arg-type-hints-in-docstring=false
          - --check-return-types=false
          - --check-yield-types=false
